/*
Copyright 2023 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// loadbalancer defines haproxy configuration that is used for the cluster load balancer.
// it is based on code from capd, with specific adjustments to work in LXC environments.
package loadbalancer

import (
	"bytes"
	"fmt"
	"net"
	"text/template"
)

// ConfigData is supplied to the loadbalancer config template.
type ConfigData struct {
	FrontendControlPlanePort string
	BackendControlPlanePort  string
	BackendServers           map[string]BackendServer
	IPv6                     bool
}

// BackendServer defines a loadbalancer backend.
type BackendServer struct {
	Address string
	Weight  int
}

// DefaultTemplate is the loadbalancer config template.
const DefaultTemplate = `# generated by kind
global
  log /dev/log local0
  log /dev/log local1 notice
  daemon
  # limit memory usage to approximately 18 MB
  # (see https://github.com/kubernetes-sigs/kind/pull/3115)
  maxconn 100000

# NOTE(neoaggelos): resolvers entry is removed, we instead configure the instance addresses on the backends

defaults
  log global
  mode tcp
  option dontlognull
  # TODO: tune these
  timeout connect 5000
  timeout client 50000
  timeout server 50000
  # allow to boot despite dns don't resolve backends
  default-server init-addr none

frontend stats
  mode http
  bind *:8404
  stats enable
  stats uri /stats
  stats refresh 1s
  stats admin if TRUE

frontend control-plane
  bind *:{{ .FrontendControlPlanePort }}
  {{ if .IPv6 -}}
  bind :::{{ .FrontendControlPlanePort }};
  {{- end }}
  default_backend kube-apiservers

backend kube-apiservers
  option httpchk GET /healthz
  {{range $server, $backend := .BackendServers}}
  server {{ $server }} {{ JoinHostPort $backend.Address $.BackendControlPlanePort }} weight {{ $backend.Weight }} check check-ssl verify none
  {{- end}}
`

// Config generates the loadbalancer config from the ConfigTemplate and ConfigData.
func Config(data *ConfigData, configTemplate string) (config []byte, err error) {
	t, err := template.New("loadbalancer-config").Funcs(template.FuncMap{
		"JoinHostPort": net.JoinHostPort,
	}).Parse(configTemplate)
	if err != nil {
		return nil, fmt.Errorf("failed to parse config template: %w", err)
	}
	// execute the template
	var buff bytes.Buffer
	err = t.Execute(&buff, data)
	if err != nil {
		return nil, fmt.Errorf("error executing config template: %w", err)
	}
	return buff.Bytes(), nil
}
