apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ${POD_CIDR:=[10.244.0.0/16]}
    services:
      cidrBlocks: ${SERVICE_CIDR:=[10.96.0.0/12]}
    serviceDomain: cluster.local
  topology:
    class: lxc-default
    version: ${KUBERNETES_VERSION}
    controlPlane:
      replicas: ${CONTROL_PLANE_MACHINE_COUNT:=1}
    variables:
    # Cluster configuration
    - name: secretRef
      value: ${LXC_SECRET_NAME}
    - name: loadBalancer
      value:
        ${LOAD_BALANCER}

        ## LOAD_BALANCER can be one of:
        # lxc: {profiles: [default], flavor: c1-m1}
        # oci: {profiles: [default], flavor: c1-m1}
        # kube-vip: {host: 10.0.42.1}
        # ovn: {host: 10.100.42.1, networkName: default}

    # Control plane instance configuration
    - name: instance
      value:
        type: ${CONTROL_PLANE_MACHINE_TYPE:=container}
        flavor: ${CONTROL_PLANE_MACHINE_FLAVOR:=c2-m4}
        profiles: ${CONTROL_PLANE_MACHINE_PROFILES:=[default]}
        image: ${LXC_IMAGE_NAME:=""}
        installKubeadm: ${INSTALL_KUBEADM:=false}

    # CNI
    - name: deployKubeFlannel
      value: ${DEPLOY_KUBE_FLANNEL:=false}

    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        metadata:
          annotations:
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "1"
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "5"
        variables:
          overrides:
          # Worker instance configuration
          - name: instance
            value:
              type: ${WORKER_MACHINE_TYPE:=container}
              flavor: ${WORKER_MACHINE_FLAVOR:=c2-m4}
              profiles: ${WORKER_MACHINE_PROFILES:=[default]}
              image: ${LXC_IMAGE_NAME:=""}
              installKubeadm: ${INSTALL_KUBEADM:=false}
