name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write   # for release
      packages: write   # for publishing docker images
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.2.0
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          make docker-build TAG=${{ github.ref_name }}
          make docker-push TAG=${{ github.ref_name }}

      - name: Build release assets
        run: make dist TAG=${{ github.ref_name }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: 'Release ${{ github.ref_name }}'
          tag_name: ${{ github.ref_name }}
          files: |
            dist/infrastructure-components.yaml
            dist/metadata.yaml
            dist/cluster-template*.yaml
            dist/clusterclass-*.yaml
          generate_release_notes: true
          draft: ${{ contains(github.ref_name, 'rc') }}
          prerelease: ${{ contains(github.ref_name, 'rc') }}
